version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /src/Prisma.Workspace.Web
    schedule:
      interval: weekly
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet-minor-patch:
        update-types: [minor, patch]
