import { useMemo, useState } from 'react'
import styled from 'styled-components'
import { Badge, Card, FilterRow, Grid, Kicker, Meta, Page, PageHeader, Panel, Stat } from '../components/ui'
import { activeSpecs, statusLabel } from '../lib/insights'
import type { ExplorerModel, Selection } from '../types/model'

const Board=styled.div`display:grid;grid-template-columns:repeat(4,minmax(250px,1fr));gap:14px;overflow-x:auto;align-items:start;padding-bottom:8px`
const Column=styled.section`min-height:420px;border:1px solid #d5dfe7;border-radius:14px;background:#eef3f6;padding:12px;h2{display:flex;align-items:center;justify-content:space-between;margin:2px 2px 13px;color:#24445f;font-size:14px}`
const Metrics=styled.div`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;@media(max-width:850px){grid-template-columns:repeat(2,1fr)}`

export function BacklogView({model,onSelect}:{model:ExplorerModel;onSelect:(item:Selection)=>void}){
 const [query,setQuery]=useState('');const [spec,setSpec]=useState('all');const [status,setStatus]=useState('open')
 const filtered=useMemo(()=>model.tasks.filter(task=>(status==='all'||status==='open'&&['pending','in_progress'].includes(task.status)||task.status===status)&&(spec==='all'||task.specId===spec)&&`${task.id} ${task.requirement}`.toLowerCase().includes(query.toLowerCase())),[model,query,spec,status])
 const feedbackTasks=useMemo(()=>model.storyTasks.filter(task=>(status==='all'||status==='open'&&['pending_analysis','ready','in_progress','blocked'].includes(task.status)||task.status===status)&&(spec==='all'||task.specId===spec)&&`${task.id} ${task.storyId} ${task.requirement}`.toLowerCase().includes(query.toLowerCase())),[model,query,spec,status])
 const count=(value:string)=>model.tasks.filter(task=>task.status===value).length
 return <Page><PageHeader><div><Kicker>Fila técnica de implementação</Kicker><h1>Trabalho dos agentes</h1><p>Reúne tarefas planejadas pelas specs e tarefas geradas automaticamente por observações da homologação.</p></div><Badge>{filtered.length+feedbackTasks.length}/{model.tasks.length+model.storyTasks.length} tarefas visíveis</Badge></PageHeader>
 <Metrics><Stat><span>Pendentes</span><strong>{count('pending')}</strong></Stat><Stat><span>Em andamento</span><strong>{count('in_progress')}</strong></Stat><Stat><span>Concluídas</span><strong>{count('completed')}</strong></Stat><Stat><span>Canceladas</span><strong>{count('cancelled')}</strong></Stat></Metrics>
 <FilterRow><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tarefa, história ou requisito"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Somente abertas</option><option value="all">Todos os status</option><option value="pending_analysis">Aguardando análise da IA</option><option value="pending">Pendentes</option><option value="in_progress">Em andamento</option><option value="completed">Concluídas</option><option value="archived">Arquivadas</option><option value="cancelled">Canceladas</option></select><select value={spec} onChange={e=>setSpec(e.target.value)}><option value="all">Todas as specs ativas</option>{activeSpecs(model).map(item=><option key={item.id}>{item.id}</option>)}</select></FilterRow>
 {feedbackTasks.length>0&&<Panel><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:12,flexWrap:'wrap'}}><div><h2>Tarefas geradas pela homologação</h2><p>Uma observação ou comportamento ausente cria uma tarefa de análise. A IA decide se deve corrigir código, implementar algo faltante ou revisar história e spec.</p></div><Badge $tone="warning">{feedbackTasks.length} aguardando fluxo</Badge></div><Grid $columns={3}>{feedbackTasks.map(task=><Card key={task.id} onClick={()=>onSelect({...task,_eyebrow:'Tarefa gerada pela homologação',_summary:task.requirement,relatedStory:model.userStories.find(story=>story.id===task.storyId),relatedSpec:model.specs.find(item=>item.id===task.specId)})}><Meta><Badge>{task.storyId}</Badge><Badge $tone="warning">{statusLabel(task.status)}</Badge></Meta><h3>{task.title}</h3><p>{task.requirement}</p><Meta style={{marginTop:12,marginBottom:0}}><Badge $tone="neutral">{task.id}</Badge><Badge $tone="neutral">triagem da IA</Badge></Meta></Card>)}</Grid></Panel>}
 <Board>{['P0','P1','P2','P3'].map(priority=>{const tasks=filtered.filter(task=>task.priority===priority);return <Column key={priority}><h2><span>{priority}</span><Badge $tone={priority==='P0'?'error':priority==='P1'?'warning':'neutral'}>{tasks.length}</Badge></h2>{tasks.map(task=><Card key={task.id} style={{marginBottom:10}} onClick={()=>onSelect({...task,title:task.id,_eyebrow:'Tarefa para os agentes',_summary:task.requirement,relatedSpec:model.specs.find(item=>item.id===task.specId),requiredGates:task.gates,contextPlan:model.context.taskContexts.find(item=>item.taskId===task.id)})}><Meta><Badge>{task.id}</Badge><Badge $tone={task.status==='completed'?'success':task.status==='in_progress'?'warning':task.status==='cancelled'?'neutral':'blue'}>{statusLabel(task.status)}</Badge></Meta><p>{task.requirement}</p><Meta style={{marginTop:12,marginBottom:0}}><Badge $tone="neutral">{task.specId}</Badge>{task.gates.length>0&&<Badge $tone="neutral">{task.gates.length} gates</Badge>}</Meta></Card>)}</Column>})}</Board></Page>
}
