import { useMemo, useState } from 'react'
import styled from 'styled-components'
import { Badge, FilterRow, Kicker, Meta, Page, PageHeader, Panel, Segmented, Split, Stat } from '../components/ui'
import { traduzir } from '../lib/i18n'
import type { ContextArtifact, ContextPlan, ExplorerModel, Selection } from '../types/model'

const Steps = styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;@media(max-width:900px){grid-template-columns:1fr}.step{display:grid;grid-template-columns:34px minmax(0,1fr);gap:11px;align-items:start;border:1px solid #d9e2e9;border-radius:12px;background:#fff;padding:13px}.number{display:grid;width:30px;height:30px;place-items:center;border-radius:9px;background:#eaf4fa;color:#166da9;font-weight:800}.step strong{display:block;margin:1px 0 4px;color:#183149}.step p{margin:0;color:#67798b;font-size:12px;line-height:1.45}`
const Metrics = styled.div`display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;@media(max-width:800px){grid-template-columns:1fr}`
const Groups = styled.div`display:grid;gap:10px;margin-top:14px;`
const ArtifactGroup = styled.details`border:1px solid #d9e2e9;border-radius:11px;background:#fff;overflow:hidden;summary{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:13px 14px;color:#19344d;font-weight:750;cursor:pointer;list-style:none}summary::-webkit-details-marker{display:none}.files{border-top:1px solid #e5ebef}.file{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;width:100%;border:0;border-bottom:1px solid #edf1f4;background:#fff;padding:11px 14px;text-align:left;cursor:pointer}.file:last-child{border-bottom:0}.file:hover{background:#f7fafc}.path{display:block;color:#24577c;overflow-wrap:anywhere}.reason{display:block;margin-top:4px;color:#778696;font-size:11px}.inspect{align-self:center;color:#1671b8;font-size:11px;font-weight:750}`
const CategoryList = styled.div`display:grid;gap:8px;margin-top:13px;.row{display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid #edf1f4;padding:8px 0}.row:last-child{border-bottom:0}.row strong{color:#294761}.row small{display:block;margin-top:2px;color:#7a8897}`

const categoryPurpose:Record<string,string>={Bootstrap:'Regras básicas que sempre precisam ser lidas.',Spec:'Comportamento esperado para este trabalho.','Source Code':'Arquivos do produto que podem ser afetados.',Tests:'Testes que comprovam o comportamento.',Gates:'Comandos automáticos que precisam passar.',Contracts:'Limites e responsabilidades dos agentes.',Dependencies:'Código externo ao domínio imediato.',Database:'Schema e migrations relacionados.',Docs:'Documentação complementar.',History:'Histórico necessário para entender decisões anteriores.'}
const gateNames:Record<string,[string,string]>={backend_build:['Compilar o backend','Confirma que o código .NET compila sem erros.'],backend_test:['Testar o backend','Executa os testes automatizados do backend.'],frontend_build:['Compilar o frontend','Confirma que TypeScript e o bundle React são gerados.'],frontend_test:['Testar o frontend','Executa os testes automatizados da interface.'],frontend_lint:['Analisar o frontend','Procura problemas de qualidade e padronização no código.']}
function gateKey(path:string){return path.split('gates.')[1]??''}
function artifactName(item:ContextArtifact){return item.category==='Gates'?(gateNames[gateKey(item.path)]?.[0]??'Verificação automática'):item.path}
function artifactReason(item:ContextArtifact){return item.category==='Gates'?(gateNames[gateKey(item.path)]?.[1]??item.reason):item.reason}

export function ContextView({model,onSelect}:{model:ExplorerModel;onSelect:(item:Selection)=>void}){
  const [scope,setScope]=useState<'domain'|'spec'|'task'>('domain')
  const options=scope==='domain'?model.context.domainContexts:scope==='spec'?model.context.specContexts:model.context.taskContexts
  const [selected,setSelected]=useState(model.context.domainContexts[0]?.id??'')
  const [depth,setDepth]=useState<'minimum'|'expanded'>('minimum')
  const plan=useMemo(()=>(options.find(item=>item.id===selected)??options[0]) as ContextPlan|undefined,[options,selected])
  const artifacts:ContextArtifact[]=plan?(depth==='minimum'?plan.minimum:[...plan.minimum,...plan.expanded]):[]
  const groups=useMemo(()=>artifacts.reduce<Record<string,ContextArtifact[]>>((result,item)=>{(result[item.category]??=[]).push(item);return result},{}),[artifacts])
  const allCategories=Object.keys(plan?.categoryStates??{})
  const selectedCategories=new Set(artifacts.map(item=>item.category))
  const chooseScope=(value:typeof scope)=>{setScope(value);const next=value==='domain'?model.context.domainContexts:value==='spec'?model.context.specContexts:model.context.taskContexts;setSelected(next[0]?.id??'')}
  const title=scope==='domain'?traduzir(plan?.id??''):plan?.id??'Sem seleção'
  return <Page>
    <PageHeader><div><Kicker>Engenharia de contexto</Kicker><h1>Arquivos que a IA precisa ler</h1><p>Esta área monta uma lista controlada de arquivos antes da execução. Isso evita carregar o repositório inteiro e reduz decisões tomadas sem contexto.</p></div></PageHeader>
    <Steps><div className="step"><span className="number">1</span><div><strong>Escolha o escopo</strong><p>Domínio, especificação ou tarefa que será trabalhada.</p></div></div><div className="step"><span className="number">2</span><div><strong>Revise o plano de leitura</strong><p>Arquivos essenciais agora e complementares sob demanda.</p></div></div></Steps>
    <Panel><FilterRow><Segmented>{(['domain','spec','task'] as const).map(item=><button key={item} aria-pressed={scope===item} onClick={()=>chooseScope(item)}>{item==='domain'?'Domínio':item==='spec'?'Especificação':'Tarefa'}</button>)}</Segmented><select value={plan?.id??''} onChange={event=>setSelected(event.target.value)}>{options.map(item=><option key={item.id} value={item.id}>{scope==='domain'?traduzir(item.id):item.id}</option>)}</select><Segmented><button aria-pressed={depth==='minimum'} onClick={()=>setDepth('minimum')}>Somente essenciais</button><button aria-pressed={depth==='expanded'} onClick={()=>setDepth('expanded')}>Incluir sob demanda</button></Segmented></FilterRow></Panel>
    <Metrics><Stat><span>Arquivos essenciais</span><strong>{plan?.minimum.length??0}</strong><small>carregados antes de começar</small></Stat><Stat><span>Sob demanda</span><strong>{plan?.expanded.length??0}</strong><small>abertos somente quando necessário</small></Stat><Stat><span>Mostrados agora</span><strong>{artifacts.length}</strong><small>{depth==='minimum'?'modo essencial':'essenciais + sob demanda'}</small></Stat></Metrics>
    <Split $aside={370}><Panel><Meta><Badge>{scope==='domain'?'Domínio':scope==='spec'?'Especificação':'Tarefa'}</Badge><Badge $tone="neutral">{artifacts.length} arquivos</Badge></Meta><h2>{title}</h2><p>Os arquivos estão agrupados pelo motivo de entrada no contexto. Abra um grupo e clique num item para ver a origem técnica no Inspetor.</p><Groups>{Object.entries(groups).map(([category,items])=><ArtifactGroup key={category} open><summary><span>{traduzir(category)}</span><Badge $tone="neutral">{items.length}</Badge></summary><div className="files">{items.map(item=><button className="file" key={`${category}:${item.path}`} onClick={()=>onSelect({...item,id:item.path,title:artifactName(item),technicalPath:item.path,_eyebrow:'Arquivo de contexto',_summary:artifactReason(item)})}><span><span className="path">{artifactName(item)}</span><span className="reason">{artifactReason(item)}</span></span><span className="inspect">Inspecionar</span></button>)}</div></ArtifactGroup>)}</Groups></Panel>
    <Panel><h2>O que entra neste plano</h2><p>Verde significa incluído na seleção atual. Cinza significa que esse tipo de informação não será carregado agora.</p><CategoryList>{allCategories.map(category=><div className="row" key={category}><span><strong>{traduzir(category)}</strong><small>{categoryPurpose[category]??'Categoria do índice de contexto.'}</small></span><Badge $tone={selectedCategories.has(category)?'success':'neutral'}>{selectedCategories.has(category)?'incluído':'fora do plano'}</Badge></div>)}</CategoryList></Panel></Split>
  </Page>
}
