import { CorrectionLoopGraph } from '../components/graphs/LoopView'
import { Badge, Card, Grid, Kicker, Meta, Page, PageHeader, Panel, Split, Stat } from '../components/ui'
import type { ExplorerModel, Selection } from '../types/model'
import { traduzirNomeVerificacao } from '../lib/i18n'

export function LoopView({ model, onSelect }: { model: ExplorerModel; onSelect: (item: Selection) => void }) {
  const profile = model.loop.profile as { loop: Record<string, unknown>; productGates: Record<string, Record<string, unknown>>; missingGates: Record<string, Record<string, unknown>> }
  const policy = profile.loop
  const activeTask = model.loop.activeTask
  return <Page><PageHeader><div><Kicker>Política de correção</Kicker><h1>Ciclo de execução</h1><p>Implementar, validar, corrigir e bloquear quando a falha deixa de ser recuperável ou exige decisão humana.</p></div><Badge $tone={activeTask ? 'success' : 'neutral'}>{String(model.loop.label)}</Badge></PageHeader><Grid $columns={4}><Stat><span>Máximo</span><strong>{String(policy.max_attempts)}</strong><small>tentativas</small></Stat><Stat><span>Bloqueia após</span><strong>{String(policy.block_on_repeated_failure)}</strong><small>falhas repetidas</small></Stat><Stat><span>Verificações do produto</span><strong>{Object.keys(profile.productGates).length}</strong><small>ativas</small></Stat><Stat><span>Verificações ausentes</span><strong>{Object.keys(profile.missingGates).length}</strong><small>lacunas de operação</small></Stat></Grid><Split $aside={350}><CorrectionLoopGraph model={model} onSelect={onSelect}/><Panel><h2>Política de novas tentativas</h2><p>Falha de código volta para implementação: <strong>{policy.retry_on_fail_code ? 'sim' : 'não'}</strong>.</p><p>Falha externa consome tentativa: <strong>{policy.external_failure_counts_as_attempt ? 'sim' : 'não'}</strong>.</p><p>Falha externa bloqueia: <strong>{policy.block_on_external_failure ? 'sim' : 'não'}</strong>.</p><h3 style={{marginTop:22}}>Leitura da tentativa</h3><div style={{display:'flex',gap:9}}>{Array.from({length:Number(policy.max_attempts)},(_,index) => <Badge key={index} $tone={index === 0 ? 'blue' : 'neutral'}>{index + 1}</Badge>)}</div></Panel></Split><Panel><h2>Verificações ainda ausentes</h2><Grid $columns={2}>{Object.entries(profile.missingGates).map(([id, gate]) => <Card key={id} onClick={() => onSelect({ ...gate, id, title: traduzirNomeVerificacao(id, gate.name), _eyebrow: 'Verificação ausente' })}><Meta><Badge $tone="warning">ausente</Badge></Meta><h3>{traduzirNomeVerificacao(id, gate.name)}</h3><p>{String(gate.reason)}</p></Card>)}</Grid></Panel></Page>
}
