import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArchiveX, CheckCircle2, Clock3, Inbox, Link2, MessageSquare, Route, Search, Send, ShieldCheck, UserCheck } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import styled from 'styled-components';
import { TaskDetailDrawer } from '../components/TaskDetailDrawer';
import { previewMode, previewProject } from '../preview';
import { api } from '../services/api';
import type { ExternalRequest, ExternalRequestTriageInput } from '../types/portal';
import type { BacklogItem } from '../types/scrum';
import type { ProjectSummary } from './Projects';

interface OrganizationMember { userId:string; name:string; isActive:boolean; }
interface WorkflowProjection { stages:Array<{id:string;boardId:string;name:string}>; }

const Page = styled.section`max-width:1480px;margin:0 auto;padding:26px 30px 36px;@media(max-width:760px){padding:18px 16px;}`;
const Header = styled.header`display:flex;flex-wrap:wrap;align-items:flex-end;justify-content:space-between;gap:14px;h1{font-size:23px;}p{margin-top:5px;color:${({theme})=>theme.color.textMuted};font-size:13.5px;}`;
const SearchBox = styled.label`display:flex;min-width:min(320px,100%);min-height:36px;align-items:center;gap:7px;padding:0 10px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};background:${({theme})=>theme.color.surface};color:${({theme})=>theme.color.textMuted};input{min-width:0;flex:1;border:0;outline:0;background:transparent;font-size:13.5px;}`;
const Kpis = styled.div`display:grid;grid-template-columns:repeat(3,minmax(180px,1fr));gap:10px;margin-top:18px;@media(max-width:720px){grid-template-columns:1fr;}`;
const Kpi = styled.article`display:grid;grid-template-columns:36px minmax(0,1fr);gap:10px;align-items:center;padding:14px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.lg};background:${({theme})=>theme.color.surface};>span{display:grid;width:34px;height:34px;place-items:center;border-radius:${({theme})=>theme.radius.md};background:${({theme})=>theme.color.neutral[100]};color:${({theme})=>theme.color.brand};}small,strong{display:block;}small{color:${({theme})=>theme.color.textMuted};font-size:12px;font-weight:700;text-transform:uppercase;}strong{margin-top:3px;font-size:18px;}`;
const Queue = styled.section`margin-top:12px;overflow:hidden;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.lg};background:${({theme})=>theme.color.surface};`;
const QueueHeader = styled.header`display:flex;align-items:center;justify-content:space-between;padding:14px 16px;border-bottom:1px solid ${({theme})=>theme.color.border};h2{font-size:15px;}span{color:${({theme})=>theme.color.textMuted};font-size:12px;}`;
const Row = styled.button`display:grid;width:100%;grid-template-columns:120px minmax(220px,1fr) 170px 120px 110px;align-items:center;min-height:54px;padding:0 13px;border-bottom:1px solid ${({theme})=>theme.color.neutral[100]};color:${({theme})=>theme.color.text};font-size:13px;text-align:left;&:last-child{border-bottom:0;}&:hover{background:${({theme})=>theme.color.neutral[50]};}>*{padding:7px;}strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}@media(max-width:880px){grid-template-columns:110px minmax(180px,1fr) 110px;>*:nth-child(3),>*:nth-child(5){display:none;}}`;
const Head = styled(Row)`min-height:34px;background:${({theme})=>theme.color.neutral[50]};color:${({theme})=>theme.color.textMuted};font-size:11px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;pointer-events:none;`;
const Origin = styled.span`display:inline-flex;align-items:center;gap:5px;color:${({theme})=>theme.color.accentBlue};font-weight:750;`;
const Status = styled.span`display:inline-flex;width:fit-content;min-height:24px;align-items:center;padding:0 7px;border-radius:${({theme})=>theme.radius.pill};background:color-mix(in srgb, ${({theme})=>theme.color.accentBlue} 10%, white);font-size:11px;font-weight:800;`;
const StatusStack = styled.span`display:flex;flex-wrap:wrap;gap:4px;`;
const Empty = styled.div`display:grid;min-height:180px;place-items:center;padding:30px;color:${({theme})=>theme.color.textMuted};font-size:13.5px;text-align:center;`;
const Detail = styled.section`display:grid;grid-template-columns:minmax(0,1.2fr) minmax(300px,.8fr);gap:14px;margin-top:12px;padding:16px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.lg};background:${({theme})=>theme.color.surface};@media(max-width:850px){grid-template-columns:1fr;}`;
const Conversation = styled.div`display:grid;gap:8px;max-height:310px;overflow:auto;margin-top:12px;`;
const Message = styled.article<{ $agent:boolean }>`padding:10px;border-radius:${({theme})=>theme.radius.md};background:${({$agent,theme})=>$agent?`color-mix(in srgb, ${theme.color.accentBlue} 9%, white)`:theme.color.neutral[50]};strong{display:block;font-size:12px;}p{margin-top:4px;font-size:13px;line-height:1.5;white-space:pre-wrap;}small{display:block;margin-top:4px;color:${({theme})=>theme.color.textMuted};font-size:11px;}`;
const Reply = styled.form`display:grid;gap:8px;textarea{min-height:94px;padding:9px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};resize:vertical;font:inherit;}button{display:inline-flex;width:fit-content;min-height:34px;align-items:center;gap:6px;padding:0 11px;border-radius:${({theme})=>theme.radius.md};background:${({theme})=>theme.color.brand};color:${({theme})=>theme.color.onBrand};font-size:13px;font-weight:800;}`;
const OpenTask = styled.button`display:inline-flex;min-height:34px;align-items:center;gap:6px;margin-top:10px;padding:0 10px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};font-size:13px;font-weight:800;`;
const Side=styled.aside`display:grid;align-content:start;gap:12px;`;
const Triage=styled.section`display:grid;gap:10px;padding:12px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};h3{font-size:13.5px;}p{color:${({theme})=>theme.color.textMuted};font-size:12px;line-height:1.5;}`;
const Quick=styled.div`display:flex;flex-wrap:wrap;gap:6px;button{display:inline-flex;min-height:31px;align-items:center;gap:5px;padding:0 8px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};font-size:12px;font-weight:800;}button.primary{background:${({theme})=>theme.color.brand};color:${({theme})=>theme.color.onBrand};}button.danger{border-color:${({theme})=>theme.color.danger};color:${({theme})=>theme.color.danger};}`;
const Controls=styled.div`display:grid;grid-template-columns:1fr 1fr;gap:7px;label{display:grid;gap:3px;color:${({theme})=>theme.color.textMuted};font-size:11px;font-weight:800;}input,select{width:100%;min-height:32px;padding:0 7px;border:1px solid ${({theme})=>theme.color.border};border-radius:6px;font-size:12px;}label.wide{grid-column:1/-1;}button{min-height:32px;border-radius:6px;background:${({theme})=>theme.color.brand};color:white;font-size:12px;font-weight:800;}@media(max-width:500px){grid-template-columns:1fr;label.wide{grid-column:auto;}}`;
const Audit=styled.div`display:grid;gap:5px;max-height:190px;overflow:auto;article{padding:7px;border-left:2px solid ${({theme})=>theme.color.accentBlue};background:${({theme})=>theme.color.neutral[50]};strong{display:block;font-size:11px;}p{margin-top:2px;font-size:11px;}small{font-size:10px;color:${({theme})=>theme.color.textMuted};}}`;

const previewRequests:ExternalRequest[] = previewMode ? [
  {id:'request-1',protocol:'2026-004821',projectId:previewProject.id,projectKey:previewProject.key,projectName:previewProject.name,boardId:previewProject.boards[0]?.id??'',workItemId:'request-0001',workItemNumber:4821,title:'Erro ao emitir comprovante de licenciamento',description:'O portal retorna indisponibilidade ao concluir a emissão.',status:'Nova',priority:2,requesterName:'Maria Oliveira',requesterEmail:'maria@example.com',triageStatus:1,createdAt:'2026-07-15T14:20:00Z',updatedAt:'2026-07-15T14:20:00Z',submittedValues:{},triageEvents:[],messages:[],attachments:[]},
] : [];

const age = (value:string) => {
  const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));
  return minutes<60?`${minutes} min`:`${Math.floor(minutes/60)}h ${minutes%60}min`;
};
const triageStatusLabels:Record<number,string>={1:'Nova',2:'Aceita',3:'Aguardando informações',4:'Recusada',5:'Duplicada',6:'Encaminhada'};
export function Requests(){
  const queryClient=useQueryClient();
  const [search,setSearch]=useState('');
  const [selected,setSelected]=useState<ExternalRequest|null>(null);
  const [drawerOpen,setDrawerOpen]=useState(false);
  const [reply,setReply]=useState('');
  const [triage,setTriage]=useState({category:'',priority:1,responsibleId:'',teamId:'',projectId:'',boardId:'',stageId:'',relatedNumber:''});
  const requestsQuery=useQuery<ExternalRequest[]>({queryKey:['external-requests'],retry:false,queryFn:async()=>{try{return await api.getExternalRequests();}catch(error){if(previewMode)return previewRequests;throw error;}}});
  const projectsQuery=useQuery<ProjectSummary[]>({queryKey:['projects','triage'],queryFn:()=>api.getProjects(true),enabled:!previewMode,initialData:previewMode?[previewProject]:undefined});
  const membersQuery=useQuery<OrganizationMember[]>({queryKey:['organization','members'],queryFn:()=>api.getOrganizationMembers(),enabled:!previewMode});
  const workflowQuery=useQuery<WorkflowProjection>({queryKey:['workflow',triage.projectId],queryFn:()=>api.getProjectWorkflow(triage.projectId),enabled:!previewMode&&Boolean(triage.projectId)});
  const targetProject=projectsQuery.data?.find(project=>project.id===triage.projectId);
  const targetStages=workflowQuery.data?.stages.filter(stage=>stage.boardId===triage.boardId)??[];
  const targetMemberIds=new Set(targetProject?.members?.map(member=>member.userId)??[]);
  const targetMembers=membersQuery.data?.filter(member=>member.isActive&&targetMemberIds.has(member.userId))??[];
  useEffect(()=>{if(selected)setTriage({category:selected.category??'',priority:selected.priority,responsibleId:selected.responsibleId??'',teamId:selected.teamId??'',projectId:selected.projectId,boardId:selected.boardId,stageId:selected.stageId??'',relatedNumber:''});},[selected]);
  const normalized=search.trim().toLocaleLowerCase('pt-BR');
  const requests=useMemo(()=>(requestsQuery.data??[]).filter(item=>!normalized||`${item.protocol} ${item.title} ${item.requesterName}`.toLocaleLowerCase('pt-BR').includes(normalized)),[requestsQuery.data,normalized]);
  const replyMutation=useMutation({mutationFn:()=>selected&&reply.trim()?api.replyToExternalRequest(selected.protocol,reply.trim()):Promise.resolve(),onSuccess:async()=>{setReply('');await queryClient.invalidateQueries({queryKey:['external-requests']});const refreshed=queryClient.getQueryData<ExternalRequest[]>(['external-requests']);setSelected(refreshed?.find(item=>item.id===selected?.id)??selected);}});
  const triageMutation=useMutation({mutationFn:(input:ExternalRequestTriageInput)=>selected?api.triageExternalRequest(selected.protocol,input):Promise.resolve(),onSuccess:async(value)=>{if(value)setSelected(value as ExternalRequest);await queryClient.invalidateQueries({queryKey:['external-requests']});}});
  const applyTriage=(action:number,extra:Partial<ExternalRequestTriageInput>={})=>triageMutation.mutate({action,...extra});
  const submit=(event:FormEvent)=>{event.preventDefault();replyMutation.mutate();};
  const drawerItem:BacklogItem|null=selected?{id:selected.workItemId,number:selected.workItemNumber,boardId:'',boardName:selected.projectName,kind:9,title:selected.title,description:selected.description,priority:selected.priority,rank:0,createdAt:selected.createdAt,completedAt:selected.completedAt}:null;
  const pending=(requestsQuery.data??[]).filter(item=>item.triageStatus===1||item.triageStatus===3).length;
  const completed=(requestsQuery.data??[]).filter(item=>item.completedAt).length;

  return <Page>
    <Header><div><h1>Solicitações</h1><p>Fila real do Portal Externo, integrada às tarefas e ao fluxo do projeto.</p></div><SearchBox><Search size={14}/><input aria-label="Buscar solicitações" placeholder="Protocolo, assunto ou solicitante..." value={search} onChange={event=>setSearch(event.target.value)}/></SearchBox></Header>
    <Kpis><Kpi><span><Inbox size={17}/></span><div><small>Aguardando atendimento</small><strong>{pending}</strong></div></Kpi><Kpi><span><MessageSquare size={17}/></span><div><small>Com interação</small><strong>{(requestsQuery.data??[]).filter(item=>item.messages.length>0).length}</strong></div></Kpi><Kpi><span><ShieldCheck size={17}/></span><div><small>Concluídas</small><strong>{completed}</strong></div></Kpi></Kpis>
    <Queue><QueueHeader><h2>Fila de triagem</h2><span>Origem, protocolo e status preservados</span></QueueHeader><Head><span>Protocolo</span><span>Solicitação</span><span>Solicitante</span><span>Status</span><span>Na fila</span></Head>
      {requests.map(item=><Row key={item.id} onClick={()=>setSelected(item)}><Origin><Inbox size={12}/>{item.protocol}</Origin><strong>{item.title}</strong><span>{item.requesterName}</span><StatusStack><Status>{triageStatusLabels[item.triageStatus]??item.status}</Status></StatusStack><span><Clock3 size={11}/> {age(item.createdAt)}</span></Row>)}
      {requestsQuery.isLoading&&<Empty>Carregando solicitações...</Empty>}{requestsQuery.error&&<Empty><AlertTriangle size={18}/><br/>{(requestsQuery.error as Error).message}</Empty>}{!requestsQuery.isLoading&&!requestsQuery.error&&requests.length===0&&<Empty>Nenhuma solicitação na fila.<br/>Novas entradas nascem no Portal Externo (Configurações do projeto → Portal habilitado + formulário publicado). Esta tela é só leitura/triagem.</Empty>}
    </Queue>
    {selected&&<Detail><div><h2>{selected.title}</h2><p style={{fontSize:13,color:'#64748b',marginTop:5}}>{selected.protocol} · {selected.projectKey} · {selected.requesterName} · {selected.externalFormTitle??'Portal Externo'}</p>{selected.description&&<p style={{fontSize:13.5,lineHeight:1.6,marginTop:12}}>{selected.description}</p>}{(selected.category||selected.relatedService||selected.requesterPhone)&&<p style={{fontSize:12,color:'#64748b',marginTop:8}}>Categoria: {selected.category||'—'} · Serviço: {selected.relatedService||'—'} · Telefone: {selected.requesterPhone||'—'}</p>}<OpenTask onClick={()=>setDrawerOpen(true)}><Inbox size={13}/>Abrir tarefa #{selected.workItemNumber}</OpenTask><Conversation>{selected.messages.map(message=><Message key={message.id} $agent={message.authorType===2}><strong>{message.authorName}</strong><p>{message.content}</p><small>{new Date(message.createdAt).toLocaleString('pt-BR')}</small></Message>)}{selected.messages.length===0&&<Empty>Ainda não há mensagens públicas.</Empty>}</Conversation></div><Side>
      <Triage><h3>Triagem · {triageStatusLabels[selected.triageStatus]??'Nova'}</h3><p>Toda ação abaixo é registrada no histórico da solicitação e da tarefa.</p>
        <Quick><button className="primary" disabled={triageMutation.isPending} onClick={()=>applyTriage(2)}><UserCheck size={11}/>Aceitar</button><button disabled={triageMutation.isPending} onClick={()=>{const text=window.prompt('Quais informações o solicitante deve complementar?');if(text)applyTriage(4,{message:text});}}><MessageSquare size={11}/>Pedir informações</button><button className="danger" disabled={triageMutation.isPending} onClick={()=>{const reason=window.prompt('Justificativa obrigatória da recusa:');if(reason)applyTriage(3,{reason});}}><ArchiveX size={11}/>Recusar</button></Quick>
        <Controls><label>Categoria<input value={triage.category} onChange={event=>setTriage({...triage,category:event.target.value})}/></label><button disabled={!triage.category||triageMutation.isPending} onClick={()=>applyTriage(5,{category:triage.category})}>Alterar categoria</button>
          <label>Prioridade<select value={triage.priority} onChange={event=>setTriage({...triage,priority:Number(event.target.value)})}><option value={0}>Baixa</option><option value={1}>Média</option><option value={2}>Alta</option><option value={3}>Crítica</option></select></label><button disabled={triageMutation.isPending} onClick={()=>applyTriage(6,{priority:triage.priority})}>Aplicar prioridade</button>
          <label>Responsável<select value={triage.responsibleId} onChange={event=>setTriage({...triage,responsibleId:event.target.value})}><option value="">Sem responsável</option>{targetMembers.map(member=><option key={member.userId} value={member.userId}>{member.name}</option>)}</select></label><button disabled={triageMutation.isPending} onClick={()=>applyTriage(7,{responsibleId:triage.responsibleId||undefined})}>Definir responsável</button>
          <label>Equipe<select value={triage.teamId} onChange={event=>setTriage({...triage,teamId:event.target.value})}><option value="">Sem equipe</option>{targetProject?.teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><button disabled={triageMutation.isPending} onClick={()=>applyTriage(8,{teamId:triage.teamId||undefined})}>Definir equipe</button>
          <label>Projeto<select value={triage.projectId} onChange={event=>{const projectId=event.target.value;const project=projectsQuery.data?.find(item=>item.id===projectId);setTriage({...triage,projectId,boardId:project?.boards[0]?.id??'',stageId:''});}}>{projectsQuery.data?.map(project=><option key={project.id} value={project.id}>{project.key} · {project.name}</option>)}</select></label><label>Quadro<select value={triage.boardId} onChange={event=>setTriage({...triage,boardId:event.target.value,stageId:''})}>{targetProject?.boards.map(board=><option key={board.id} value={board.id}>{board.name}</option>)}</select></label><button disabled={!triage.projectId||!triage.boardId||triageMutation.isPending} onClick={()=>applyTriage(9,{projectId:triage.projectId,boardId:triage.boardId})}>Relacionar ao projeto</button>
          <button disabled={triageMutation.isPending} onClick={()=>applyTriage(10)}><Route size={11}/>Enviar ao backlog</button><label>Coluna do Kanban<select value={triage.stageId} onChange={event=>setTriage({...triage,stageId:event.target.value})}><option value="">Primeira coluna</option>{targetStages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></label><button disabled={triageMutation.isPending} onClick={()=>applyTriage(11,{stageId:triage.stageId||undefined})}>Enviar ao Kanban</button>
          <label className="wide">Número de outra tarefa<input inputMode="numeric" placeholder="Ex.: 1020" value={triage.relatedNumber} onChange={event=>setTriage({...triage,relatedNumber:event.target.value})}/></label><button disabled={!triage.relatedNumber||triageMutation.isPending} onClick={()=>applyTriage(12,{relatedWorkItemNumber:Number(triage.relatedNumber)})}>Marcar duplicada</button><button disabled={!triage.relatedNumber||triageMutation.isPending} onClick={()=>applyTriage(13,{relatedWorkItemNumber:Number(triage.relatedNumber)})}><Link2 size={11}/>Vincular tarefa</button>
        </Controls>{triageMutation.error&&<p>{(triageMutation.error as Error).message}</p>}
        <Audit>{selected.triageEvents.slice().reverse().map(event=><article key={event.id}><strong>{event.actorName}</strong><p>{event.description}</p><small>{new Date(event.createdAt).toLocaleString('pt-BR')}</small></article>)}</Audit>
      </Triage>
      <Reply onSubmit={submit}><h3>Responder ao solicitante</h3><textarea required maxLength={4000} value={reply} onChange={event=>setReply(event.target.value)} placeholder="A resposta ficará visível no acompanhamento público."/><button disabled={replyMutation.isPending||!reply.trim()}><Send size={13}/>Enviar resposta</button>{selected.completionConfirmedAt&&<p><CheckCircle2 size={12}/> Conclusão confirmada pelo solicitante.</p>}</Reply>
    </Side></Detail>}
    <TaskDetailDrawer item={drawerOpen?drawerItem:null} projectKey={selected?.projectKey??'EXT'} onOpenChange={open=>{setDrawerOpen(open);if(!open)setDrawerOpen(false);}}/>
  </Page>;
}
