import { useEffect, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BellRing, Plus, Save, Trash2 } from 'lucide-react';
import styled from 'styled-components';
import { api } from '../../services/api';
import { previewMode } from '../../preview';
import type { ProjectSlaPolicy, SlaRule } from '../../types/sla';

const Section = styled.section`grid-column:1/-1;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.card};background:${({theme})=>theme.color.surface};overflow:hidden;>header{display:flex;align-items:center;gap:8px;min-height:48px;padding:0 16px;border-bottom:1px solid ${({theme})=>theme.color.border};h2{font-size:14px}small{margin-left:auto;color:${({theme})=>theme.color.textMuted};font-size:12px}}`;
const Form = styled.form`display:grid;gap:16px;padding:16px;`;
const Grid = styled.div`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;@media(max-width:850px){grid-template-columns:repeat(2,1fr)}@media(max-width:520px){grid-template-columns:1fr}`;
const Field = styled.label<{ $wide?:boolean }>`display:grid;grid-column:${({$wide})=>$wide?'1/-1':'auto'};gap:5px;color:${({theme})=>theme.color.textMuted};font-size:12px;font-weight:800;text-transform:uppercase;input,select,textarea{min-height:35px;padding:7px 9px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};font:inherit;font-size:13.5px;text-transform:none}textarea{min-height:68px;resize:vertical}`;
const Toggle = styled.label`display:flex;align-items:center;gap:7px;color:${({theme})=>theme.color.text};font-size:13px;font-weight:700;input{width:15px;height:15px}`;
const Days = styled.div`display:flex;flex-wrap:wrap;gap:7px;`;
const Day = styled.label`display:flex;align-items:center;gap:4px;padding:6px 8px;border:1px solid ${({theme})=>theme.color.border};border-radius:999px;font-size:12px;`;
const Rules = styled.div`display:grid;gap:7px;h3{font-size:13.5px}`;
const Rule = styled.div`display:grid;grid-template-columns:1.3fr 1fr 1fr 1fr auto;gap:7px;align-items:center;input,select{min-height:34px;padding:0 8px;border:1px solid ${({theme})=>theme.color.border};border-radius:${({theme})=>theme.radius.md};font-size:13px}@media(max-width:760px){grid-template-columns:1fr 1fr}.remove{color:${({theme})=>theme.color.danger}}`;
const Button = styled.button`display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:34px;padding:0 11px;border-radius:${({theme})=>theme.radius.md};background:${({theme})=>theme.color.brand};color:${({theme})=>theme.color.onBrand};font-size:13px;font-weight:800;&.secondary{justify-self:start;border:1px solid ${({theme})=>theme.color.border};background:${({theme})=>theme.color.surface};color:${({theme})=>theme.color.text}}&:disabled{opacity:.5}`;
const Footer = styled.footer`display:flex;align-items:center;justify-content:flex-end;gap:10px;border-top:1px solid ${({theme})=>theme.color.border};padding-top:14px;small{color:${({theme})=>theme.color.textMuted};font-size:12px}`;

const defaultPolicy:ProjectSlaPolicy={projectId:'',isEnabled:false,firstResponseMinutes:240,resolutionMinutes:1440,serviceStart:'08:00',serviceEnd:'18:00',businessDaysMask:62,timeZoneId:'E. South America Standard Time',pauseWhileWaitingRequester:true,alertsEnabled:true,nearDueMinutes:60,holidays:[],rules:[]};
const dayOptions=[[1,'Dom'],[2,'Seg'],[4,'Ter'],[8,'Qua'],[16,'Qui'],[32,'Sex'],[64,'Sáb']] as const;

export function ProjectSlaSettings({projectId}:{projectId:string}){
  const client=useQueryClient();
  const query=useQuery<ProjectSlaPolicy>({queryKey:['project-sla',projectId],queryFn:()=>api.getProjectSla(projectId) as Promise<ProjectSlaPolicy>,enabled:!previewMode,initialData:previewMode?{...defaultPolicy,projectId}:undefined});
  const [form,setForm]=useState<ProjectSlaPolicy>({...defaultPolicy,projectId});
  const [holidays,setHolidays]=useState('');
  useEffect(()=>{if(query.data){setForm(query.data);setHolidays(query.data.holidays.join('\n'));}},[query.data]);
  const save=useMutation({mutationFn:()=>previewMode?Promise.resolve(form):api.saveProjectSla(projectId,{...form,serviceStart:form.serviceStart.length===5?`${form.serviceStart}:00`:form.serviceStart,serviceEnd:form.serviceEnd.length===5?`${form.serviceEnd}:00`:form.serviceEnd,holidays:holidays.split(/[\s,;]+/).map(value=>value.trim()).filter(Boolean),rules:form.rules.map(({position:_,...rule})=>rule)}),onSuccess:async()=>client.invalidateQueries({queryKey:['project-sla',projectId]})});
  const setRule=(index:number,patch:Partial<SlaRule>)=>setForm(current=>({...current,rules:current.rules.map((rule,position)=>position===index?{...rule,...patch}:rule)}));
  const submit=(event:FormEvent)=>{event.preventDefault();save.mutate();};
  return <Section><header><BellRing size={16}/><h2>SLA de solicitações externas</h2><small>Prazos fotografados na abertura do protocolo</small></header><Form onSubmit={submit}>
    <Grid><Toggle><input type="checkbox" checked={form.isEnabled} onChange={event=>setForm({...form,isEnabled:event.target.checked})}/>Aplicar SLA às novas solicitações</Toggle><Toggle><input type="checkbox" checked={form.pauseWhileWaitingRequester} onChange={event=>setForm({...form,pauseWhileWaitingRequester:event.target.checked})}/>Pausar aguardando solicitante</Toggle><Toggle><input type="checkbox" checked={form.alertsEnabled} onChange={event=>setForm({...form,alertsEnabled:event.target.checked})}/>Exibir alertas de vencimento</Toggle><span/>
      <Field>Primeira resposta (min)<input type="number" min={1} required value={form.firstResponseMinutes} onChange={event=>setForm({...form,firstResponseMinutes:Number(event.target.value)})}/></Field><Field>Resolução (min)<input type="number" min={1} required value={form.resolutionMinutes} onChange={event=>setForm({...form,resolutionMinutes:Number(event.target.value)})}/></Field><Field>Atendimento inicia<input type="time" required value={form.serviceStart.slice(0,5)} onChange={event=>setForm({...form,serviceStart:event.target.value})}/></Field><Field>Atendimento termina<input type="time" required value={form.serviceEnd.slice(0,5)} onChange={event=>setForm({...form,serviceEnd:event.target.value})}/></Field>
      <Field>Alertar antes (min)<input type="number" min={1} required value={form.nearDueMinutes} onChange={event=>setForm({...form,nearDueMinutes:Number(event.target.value)})}/></Field><Field $wide>Fuso horário<input required value={form.timeZoneId} onChange={event=>setForm({...form,timeZoneId:event.target.value})}/></Field>
      <Field $wide>Dias úteis<Days>{dayOptions.map(([bit,label])=><Day key={bit}><input type="checkbox" checked={(form.businessDaysMask&bit)!==0} onChange={event=>setForm({...form,businessDaysMask:event.target.checked?form.businessDaysMask|bit:form.businessDaysMask&~bit})}/>{label}</Day>)}</Days></Field>
      <Field $wide>Feriados (aaaa-mm-dd, um por linha)<textarea value={holidays} onChange={event=>setHolidays(event.target.value)} placeholder="2026-09-07"/></Field>
    </Grid>
    <Rules><h3>Regras por categoria ou prioridade</h3>{form.rules.map((rule,index)=><Rule key={index}><input placeholder="Categoria (opcional)" value={rule.category??''} onChange={event=>setRule(index,{category:event.target.value||undefined})}/><select value={rule.priority??''} onChange={event=>setRule(index,{priority:event.target.value===''?undefined:Number(event.target.value)})}><option value="">Qualquer prioridade</option><option value={0}>Baixa</option><option value={1}>Média</option><option value={2}>Alta</option><option value={3}>Crítica</option></select><input aria-label="Prazo de primeira resposta" type="number" min={1} placeholder="1ª resposta (min)" value={rule.firstResponseMinutes??''} onChange={event=>setRule(index,{firstResponseMinutes:event.target.value?Number(event.target.value):undefined})}/><input aria-label="Prazo de resolução" type="number" min={1} placeholder="Resolução (min)" value={rule.resolutionMinutes??''} onChange={event=>setRule(index,{resolutionMinutes:event.target.value?Number(event.target.value):undefined})}/><button type="button" className="remove" aria-label="Remover regra" onClick={()=>setForm({...form,rules:form.rules.filter((_,position)=>position!==index)})}><Trash2 size={13}/></button></Rule>)}<Button type="button" className="secondary" onClick={()=>setForm({...form,rules:[...form.rules,{category:'',firstResponseMinutes:form.firstResponseMinutes,resolutionMinutes:form.resolutionMinutes}]})}><Plus size={12}/>Adicionar regra</Button></Rules>
    <Footer>{save.error&&<small>{(save.error as Error).message}</small>}{save.isSuccess&&<small>Configuração salva.</small>}<Button disabled={save.isPending}><Save size={12}/>Salvar SLA</Button></Footer>
  </Form></Section>;
}
